{% set name = "qlayers" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/alexdaniel654/qlayers/archive/v{{ version }}.tar.gz
  sha256: 3d79c2628eee4c855b8d8f2dbe4898127a5dd9d35eac49f468c06a040d08155e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python 3.9
    - pip
    - setuptools
  run:
    - python >=3.9,<4.0
    - nibabel
    - numpy
    - pandas
    - pytest
    - rtree
    - scikit-image
    - tqdm
    - trimesh

test:
  source_files:
    - qlayers
  requires:
    - pip
    - pytest
  imports:
    - qlayers
  commands:
    - pip check
    - pytest -v

about:
  home: https://github.com/alexdaniel654/qlayers
  summary: Quantitative layer analysis for renal MRI
  license: GPL-3.0-only
  license_file: LICENSE.md
  doc_url: https://qlayers.readthedocs.io/
  dev_url: https://github.com/alexdaniel654/qlayers

extra:
  recipe-maintainers:
    - alexdaniel654
